# Generated by Django 3.1.1 on 2020-09-12 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0003_auto_20200912_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Payment date')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Payment Value')),
                ('loan', models.ForeignKey(help_text='Related Loan', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
        ),
    ]
