# Generated by Django 3.1.1 on 2020-09-11 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor of Bank Loan')),
                ('interest_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Monthly interest Rate')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip address of the contract submitter')),
                ('bank', models.TextField(help_text='Bank of Loan')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Loan creation date')),
                ('client', models.ForeignKey(help_text='Loan Client', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
