# Generated by Django 3.1.1 on 2020-09-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200911_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Value of Bank Loan'),
        ),
    ]
